var cauThu_A = [
    {
     id:1,
     name:'nguyễn Thị Thùy Linh',
     age:24,
   
    },
    {
     id:2,
     name:'nguyễn Văn Mạnh',
     age:24,
    
    },
    {
     id:3,
     name:'Thành Trungs',
     age:24,
     
    },
 
 
 
 ]
 var cauThu_B = [
    {
     id:1,
     name:'nguyễn Thị Trang',
     age:24,
   
    },
    {
     id:2,
     name:'nguyễn Văn ',
     age:24,
    
    },
    {
     id:3,
     name:'Thành Trung Nhat',
     age:24,
     
    },
 
 
 
 ]
var danhSach = cauThu_A.concat(cauThu_B)
console.log(a)